name: google_maps_native_sdk
description: Native Google Maps plugin for Flutter/FlutterFlow with markers, polylines, caching, events â€” ideal for mobility apps (e.g., taxi).
version: 0.9.5
homepage: https://github.com/Nagazaki-Software/google_maps_native_sdk
repository: https://github.com/Nagazaki-Software/google_maps_native_sdk
issue_tracker: https://github.com/Nagazaki-Software/google_maps_native_sdk/issues

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.13.0"

flutter:
  plugin:
    platforms:
      android:
        package: com.example.google_maps_native_sdk
        pluginClass: GoogleMapsNativeSdkPlugin
      ios:
        pluginClass: GoogleMapsNativeSdkPlugin
      web:
        pluginClass: GoogleMapsNativeSdkWeb
        fileName: google_maps_native_sdk_web.dart

dependencies:
  flutter: { sdk: flutter }
  plugin_platform_interface: ^2.1.8
  collection: ^1.18.0
  http: ^1.1.0
  geolocator: ">=9.0.2 <15.0.0"
  flutter_tts: ^3.8.0
  flutter_web_plugins: { sdk: flutter }

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test: { sdk: flutter }
